# Generated by Django 3.2.4 on 2022-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutpost',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新日時'),
        ),
    ]
