# Generated by Django 3.2.4 on 2022-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_workoutpost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutpost',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日時'),
        ),
    ]
