# Generated by Django 3.2.4 on 2022-02-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutpost',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
