# Generated by Django 3.2.4 on 2022-04-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_auto_20220406_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutpost',
            name='comment',
            field=models.TextField(null=True, verbose_name='コメント'),
        ),
    ]
