# Generated by Django 3.2.4 on 2022-04-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_workoutpost_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutpost',
            name='comment',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='本文')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutpost', verbose_name='対象記事')),
            ],
        ),
    ]
